# Generated by Django 4.0 on 2022-12-15 17:56

import KeyPathApp.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('AccountUserName', models.CharField(max_length=20)),
                ('AccountPassword', models.CharField(max_length=20)),
                ('AccountUrl', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserFirstName', models.CharField(default='', max_length=20)),
                ('UserLastName', models.CharField(default='', max_length=20)),
                ('UserEmail', models.CharField(default='', max_length=40, unique=True)),
                ('UserPassword', models.CharField(default='', max_length=100)),
                ('UserAccounts', djongo.models.fields.ArrayField(model_container=KeyPathApp.models.Accounts)),
                ('UserToken', models.CharField(default='', max_length=64)),
                ('UserIsActive', models.IntegerField(default=0)),
            ],
        ),
    ]
