# Generated by Django 4.1.3 on 2022-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyPathApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='UserEmail',
            field=models.CharField(default='', max_length=20),
        ),
    ]
